version: "3.8"

services:
  backend:
    build:
      context: ./back-end
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: "mongodb+srv://admin:erty123@cluster0.nrmqrkm.mongodb.net/Ressources-Relationnelles?retryWrites=true&w=majority"
      SECRET_OR_KEY: "your_secret_key"

  front:
    build:
      context: ./front
    ports:
      - "8080:8080"
    environment:
      VERSION: "dev"
