name: Build and Push Docker images to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Backend dependencies
        run: npm install
        working-directory: back-end

      - name: Run Backend tests
        run: npm test
        working-directory: back-end

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: mycontainerregistycesi.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./back-end
          file: ./back-end/Dockerfile
          push: true
          tags: mycontainerregistycesi.azurecr.io/backend:latest

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: mycontainerregistycesi.azurecr.io/front:latest
